.TH AVR\-FIREWALL\-DELETE 1 "" "avr 0.1.6" "Avrea CLI"
.SH NAME
avr-firewall-delete \- Delete a rule by ID.
.SH SYNOPSIS
.B avr firewall delete
[OPTIONS] RULE_ID
.SH DESCRIPTION
Delete a rule by ID.
.PP
.SH ARGUMENTS
.TP
\fIRULE_ID\fR
\&
.SH OPTIONS
.TP
\fB\-\-org\fR \fITEXT\fR
Organization ID or slug. Uses default org if not specified.
.TP
\fB\-\-repo\fR \fITEXT\fR
Repository ID. If provided, deletes a repo-level rule.
.SH SEE ALSO
.BR avr (1),
.BR avr-firewall (1),
.BR avr-firewall-add (1),
.BR avr-firewall-flow-summaries (1),
.BR avr-firewall-list (1),
.BR avr-firewall-move (1),
.BR avr-firewall-set-default (1),
.BR avr-firewall-show (1)
