.TH AVR\-CONFIG\-GET 1 "" "avr 0.1.6" "Avrea CLI"
.SH NAME
avr-config-get \- Print the value of a configuration key.
.SH SYNOPSIS
.B avr config get
[OPTIONS] {org}
.SH DESCRIPTION
Print the value of a configuration key.
.PP
.RS 4
.nf
Available keys:
  org   Active organization ID
.fi
.RE
.SH ARGUMENTS
.TP
\fIKEY\fR
(choices: org)
.SH SEE ALSO
.BR avr (1),
.BR avr-config (1),
.BR avr-config-list (1),
.BR avr-config-set (1),
.BR avr-config-unset (1)
