.TH AVR\-REPO 1 "" "avr 0.1.6" "Avrea CLI"
.SH NAME
avr-repo \- Manage repositories and public mirrors.
.SH SYNOPSIS
.B avr repo
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage repositories and public mirrors.
.PP
.SH COMMANDS
.TP
list
List repositories you can access in an organization.
.TP
public-mirror
Request and browse mirrors of public GitHub repositories.
.SH SEE ALSO
.BR avr (1),
.BR avr-status (1),
.BR avr-run (1),
.BR avr-job (1),
.BR avr-vm (1),
.BR avr-workflow (1),
.BR avr-cache (1),
.BR avr-log (1),
.BR avr-auth (1),
.BR avr-config (1),
.BR avr-settings (1),
.BR avr-firewall (1),
.BR avr-billing (1),
.BR avr-audit-events (1),
.BR avr-org (1),
.BR avr-health (1),
.BR avr-repo-list (1),
.BR avr-repo-public-mirror (1)
