.TH AVR\-RUN\-CANCEL 1 "" "avr 0.1.3" "Avrea CLI"
.SH NAME
avr-run-cancel \- Cancel an in-progress or queued workflow run.
.SH SYNOPSIS
.B avr run cancel
[OPTIONS] RUN_ID
.SH DESCRIPTION
Cancel an in-progress or queued workflow run.
.PP
.RS 4
.nf
Examples:
    avr run cancel run-abc123
    avr run cancel run-abc123 --yes
.fi
.RE
.SH ARGUMENTS
.TP
\fIRUN_ID\fR
\&
.SH OPTIONS
.TP
\fB\-\-org\fR \fITEXT\fR
Organization ID.
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip the confirmation prompt.
.SH SEE ALSO
.BR avr (1),
.BR avr-run (1),
.BR avr-run-list (1),
.BR avr-run-logs (1),
.BR avr-run-rerun (1),
.BR avr-run-view (1),
.BR avr-run-watch (1)
