.TH AVR\-ORG\-INSTALL 1 "" "avr 0.1.5" "Avrea CLI"
.SH NAME
avr-org-install \- Manage GitHub App installations.
.SH SYNOPSIS
.B avr org install
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage GitHub App installations.
.PP
.SH COMMANDS
.TP
add
Start the GitHub App installation flow.
.TP
list
List accessible installations across all your organizations.
.TP
remove
Remove/suspend a GitHub installation.
.SH SEE ALSO
.BR avr (1),
.BR avr-org (1),
.BR avr-org-create (1),
.BR avr-org-email-domain (1),
.BR avr-org-list (1),
.BR avr-org-members (1),
.BR avr-org-install-add (1),
.BR avr-org-install-list (1),
.BR avr-org-install-remove (1)
