.TH AVR\-ORG\-EMAIL\-DOMAIN 1 "" "avr 0.1.3" "Avrea CLI"
.SH NAME
avr-org-email-domain \- Manage email domains for automatic org membership.
.SH SYNOPSIS
.B avr org email-domain
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage email domains for automatic org membership.
.PP
.SH COMMANDS
.TP
list
List email domains for automatic org membership (admin only).
.TP
set
Set email domains for automatic org membership (admin only).
.SH SEE ALSO
.BR avr (1),
.BR avr-org (1),
.BR avr-org-create (1),
.BR avr-org-install (1),
.BR avr-org-list (1),
.BR avr-org-members (1),
.BR avr-org-email-domain-list (1),
.BR avr-org-email-domain-set (1)
