.TH AVR\-FIREWALL\-SHOW 1 "" "avr 0.1.0" "Avrea CLI"
.SH NAME
avr-firewall-show \- Show the resolved (merged) firewall rule list for a repository.
.SH SYNOPSIS
.B avr firewall show
[OPTIONS]
.SH DESCRIPTION
Show the resolved (merged) firewall rule list for a repository.
.PP
.SH OPTIONS
.TP
\fB\-\-org\fR \fITEXT\fR
Organization ID. Uses default org if not specified.
.TP
\fB\-\-repo\fR \fITEXT\fR
Repository ID. (required)
.TP
\fB\-\-json\fR
Output resolved rules as JSON instead of a table.
.SH SEE ALSO
.BR avr (1),
.BR avr-firewall (1),
.BR avr-firewall-add (1),
.BR avr-firewall-delete (1),
.BR avr-firewall-flow-summaries (1),
.BR avr-firewall-list (1),
.BR avr-firewall-move (1),
.BR avr-firewall-set-default (1)
