.TH AVR\-CONFIG\-LIST 1 "" "avr 0.1.6" "Avrea CLI"
.SH NAME
avr-config-list \- Show the active CLI configuration (host, auth, org, default repo).
.SH SYNOPSIS
.B avr config list
[OPTIONS]
.SH DESCRIPTION
Show the active CLI configuration (host, auth, org, default repo).
.PP
.SH SEE ALSO
.BR avr (1),
.BR avr-config (1),
.BR avr-config-get (1),
.BR avr-config-set (1),
.BR avr-config-unset (1)
