.TH AVR\-BILLING\-PAYMENT\-METHODS\-REMOVE 1 "" "avr 0.1.1" "Avrea CLI"
.SH NAME
avr-billing-payment-methods-remove \- Remove a payment method.
.SH SYNOPSIS
.B avr billing payment-methods remove
[OPTIONS] PM_ID
.SH DESCRIPTION
Remove a payment method.
.PP
.SH ARGUMENTS
.TP
\fIPM_ID\fR
\&
.SH OPTIONS
.TP
\fB\-\-org\fR \fITEXT\fR
Organization ID. Uses default org if not specified (see: avr config set org).
.TP
\fB\-\-yes\fR
Skip confirmation prompt.
.SH SEE ALSO
.BR avr (1),
.BR avr-billing-payment-methods (1),
.BR avr-billing-payment-methods-add (1),
.BR avr-billing-payment-methods-list (1),
.BR avr-billing-payment-methods-set-default (1)
