.TH AVR\-BILLING\-INVOICES 1 "" "avr 0.1.2" "Avrea CLI"
.SH NAME
avr-billing-invoices \- Manage invoices.
.SH SYNOPSIS
.B avr billing invoices
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage invoices.
.PP
.SH COMMANDS
.TP
download
Download an invoice PDF.
.TP
list
List invoices.
.TP
show
Show details for a single invoice.
.SH SEE ALSO
.BR avr (1),
.BR avr-billing (1),
.BR avr-billing-payment-methods (1),
.BR avr-billing-settings (1),
.BR avr-billing-summary (1),
.BR avr-billing-update-settings (1),
.BR avr-billing-invoices-download (1),
.BR avr-billing-invoices-list (1),
.BR avr-billing-invoices-show (1)
