.TH AVR\-REPO\-MIRROR 1 "" "avr 0.1.6" "Avrea CLI"
.SH NAME
avr-repo-mirror \- Create and manage avrea-git mirrors of your repositories.
.SH SYNOPSIS
.B avr repo mirror
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Create and manage avrea-git mirrors of your repositories.
.PP
.SH COMMANDS
.TP
create
Create an avrea-git mirror for a repository.
.TP
delete
Disable a repository's avrea-git mirror.
.TP
status
Show a repository's avrea-git mirror status.
.SH SEE ALSO
.BR avr (1),
.BR avr-repo (1),
.BR avr-repo-list (1),
.BR avr-repo-public-mirror (1),
.BR avr-repo-mirror-create (1),
.BR avr-repo-mirror-delete (1),
.BR avr-repo-mirror-status (1)
