.TH AVR\-BILLING\-PAYMENT\-METHODS 1 "" "avr 0.2.0" "Avrea CLI"
.SH NAME
avr-billing-payment-methods \- Manage payment methods.
.SH SYNOPSIS
.B avr billing payment-methods
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage payment methods.
.PP
.SH COMMANDS
.TP
add
Add a credit card as a payment method.
.TP
list
List payment methods.
.TP
remove
Remove a payment method.
.TP
set-default
Set a payment method as the default.
.SH SEE ALSO
.BR avr (1),
.BR avr-billing (1),
.BR avr-billing-invoices (1),
.BR avr-billing-settings (1),
.BR avr-billing-summary (1),
.BR avr-billing-update-settings (1),
.BR avr-billing-payment-methods-add (1),
.BR avr-billing-payment-methods-list (1),
.BR avr-billing-payment-methods-remove (1),
.BR avr-billing-payment-methods-set-default (1)
